### ISSUE TITLE
start chat screen

### ISSUE THREAD

**Issue by grarer** [GRarer/boop#29]
the screen where the user will be taken when clicking on a push notification should show their friend's name and list of contact methods for contacting them. there are two major design decisions we need to address:

- is it feasible to have clickable links for some common chat platforms? If so, will it look okay to merge clickable and nonclickable contact cards, since we certainly can't have clickable links for every chat platform?
- do we need to keep people's contact methods private so that only their friends can see them?  authenticating this permission would be difficult since we can't guarantee that the user will be signed in when they get the notification, and it would probably require us to transmit extra information in the notification body.

**Comment by jelloshots13** [comment]
Look out for a preview tomorrow morn or afternoon. Light feedback would be appreciated so that I can make revisions ahead of our Monday meeting :smile:
