### ISSUE TITLE
spontaneous push notifications algorithm planning

### ISSUE THREAD

**Issue by grarer** [GRarer/boop#30]
the backend will need to decide when to send notifications to which pairs of friends or friends-of-friends. so far this has been a black box in our design, but we need to figure out exactly how it should work before we can implement the core feature of our product.

**Comment by sanjujampana** [comment]
For the push notifications, we want to take a random sample of users to check for who a notification should be sent to. Then, after identifying users who have not gotten a notification in a bit, we will send notifications to the user and a friend of theirs. We will send the same amount of notifications to users, no matter the amount of friends.
