### ISSUE TITLE
add more notification message templates

### ISSUE THREAD

**Issue by grarer** [GRarer/boop#51]
when we send notifications, we randomly choose from a list of templates that we fill out with the friend's name and pronouns. adding more of them would increase variety and could make our app be perceived as more lively and friendly.

**Comment by GRarer** [comment]
we decided in  today's meeting that having direct links to profiles on some platforms was not worth creating inconsistency between platforms (based on the difficulty we've had testing and validating platform links), so there's no need to add links to platforms. however, we still want to add the names and icons of more chat platforms, including some social media platforms.

**Comment by grarer** [comment]
The reminder templates for friends and for friends-of-friends are defined in `backend/src/services/reminders/reminderNotificationMessages.ts`

`friendTemplates` is the list of message templates used for a notification about a friend, and `metafriendTemplates` is the list of message templates used for friend-of-friend notifications.

```ts
const friendTemplates: ((friend: NotificationIdentity) => string)[] = [
  (friend) => `Say hi to ${friend.friendlyName}`,
  (friend) => `Catch up with ${friend.fullName}`,
  (friend) => `Would you like to chat with ${friend.friendlyName} today?`,
  (friend) => `How is ${friend.friendlyName} doing today? Check in on ${pronouns(friend.gender).object} and find out!`
];

const metafriendTemplates: ((metafriend: NotificationIdentity, mutualFriend: NotificationIdentity) => string)[] = [
  (metafriend, mutualFriend) =>
    `Say hello to someone in your circles. You and ${metafriend.fullName} are both friends with ${
      mutualFriend.friendlyName}. Would you like to chat with ${pronouns(metafriend.gender).object}?`,
  (metafriend, mutualFriend) => `You and ${metafriend.fullName} are both friends with ${
    mutualFriend.friendlyName}. Would you like to say "hi" to ${pronouns(metafriend.gender).object}?`,
];
```

The `pronouns` function returns an object of the pronouns for different cases (subject, object, possessive, etc), defaulting to neutral pronouns if the gender is unspecified. See `core/src/datatypes/gender.ts` if you're curious about the implementation.

To test the appearance of notifications templates, you can log into the app as the admin user and run `admin.triggerPair('alice', 'bob');` in the browser console to trigger a push reminding Alice to talk to Bob (and vice versa), or use `admin.triggerPair('alice', 'david', 'charlie')` to send notifications to Alice and David telling them that they are both friends with Charlie. Note that subscribing to and receiving notifications is only possible in PWA mode, and also doesnt work in incognito.
